# GEN AI
1. What is Generative AI?
>>Generative AI is a type of artificial intelligence that can create new content such as text, images, audio, and code by learning patterns from existing data.
Use Cases:
Healthcare → Drug discovery
Finance → Fraud detection reports
Education → Content generation
Entertainment → Story, music creation
Business → Chatbots, marketing content

2. Probabilistic Modeling
>>Generative models use probability distributions to generate new data similar to training data.
Difference:
Generative Model → Learns data distribution (P(X))
Discriminative Model → Learns decision boundary (P(Y|X))

3. Autoencoder vs VAE
>>Feature	Autoencoder	VAE
Output	Same as input	Probabilistic output
Nature	Deterministic	Probabilistic
Use	Compression	Text/Image generation

4. Attention in NMT
>>Attention mechanism allows the model to focus on important words during translation.
Example:
While translating “The cat sat on mat”
It focuses on correct word mapping
important-
Improves accuracy
Handles long sentences
Better context understanding

5. Ethical Considerations
>>Bias in generated content
Plagiarism issues
Fake content / misinformation
Copyright concerns
Misuse (deepfake, spam)

10. Creative Writing Assistant
>>System Design:
Model → GPT-2 / GPT-4
Data → Books, stories, scripts
Features:
Story generation
Character creation
Plot suggestions
Challenges:
Bias
Content quality
Ethical issues
Evaluation:
Human review
BLEU score
User feedback

In [1]:
#6. VAE for Text (Simplified Code)
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

texts = ["The sky is blue", "The sun is bright", "The grass is green",
         "The night is dark", "The stars are shining"]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)

padded = pad_sequences(sequences)

print(padded)

[[ 1  3  2  4]
 [ 1  5  2  6]
 [ 1  7  2  8]
 [ 1  9  2 10]
 [ 1 11 12 13]]


In [2]:
#7. GPT Translation
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

text = "AI is transforming the world."

# French Translation
model_name_fr = "Helsinki-NLP/opus-mt-en-fr"
tokenizer_fr = AutoTokenizer.from_pretrained(model_name_fr)
model_fr = AutoModelForSeq2SeqLM.from_pretrained(model_name_fr)

inputs_fr = tokenizer_fr(text, return_tensors="pt")
outputs_fr = model_fr.generate(**inputs_fr)
translated_text_fr = tokenizer_fr.decode(outputs_fr[0], skip_special_tokens=True)
print(f"English to French: {translated_text_fr}")

# German Translation
model_name_de = "Helsinki-NLP/opus-mt-en-de"
tokenizer_de = AutoTokenizer.from_pretrained(model_name_de)
model_de = AutoModelForSeq2SeqLM.from_pretrained(model_name_de)

inputs_de = tokenizer_de(text, return_tensors="pt")
outputs_de = model_de.generate(**inputs_de)
translated_text_de = tokenizer_de.decode(outputs_de[0], skip_special_tokens=True)
print(f"English to German: {translated_text_de}")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")


Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

English to French: L'IA transforme le monde.


Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

English to German: KI transformiert die Welt.


In [3]:
#8. Encoder-Decoder Model (Simple)
import tensorflow as tf

encoder = tf.keras.layers.LSTM(64, return_state=True)
decoder = tf.keras.layers.LSTM(64, return_sequences=True)


In [4]:
#9. Poem Generation (GPT)
from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

prompt = "Roses are red, violets are blue,"
print(generator(prompt, max_length=30))

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

Passing `generation_config` together with generation-related arguments=({'max_length'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=30) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


[{'generated_text': 'Roses are red, violets are blue, and oocytes are black.\n\nIn a previous study, we found that the oocyte-specific antigen (O antigen) and the oocyte-specific antigen (O antigen+) were more complex than those in different animals. This finding suggests that the oocyte-specific antigen may be more strongly expressed in the human oocyte than in the oocyte-specific antigen.\n\nThe following lines of evidence suggest that the oocyte-specific antigen may be less strongly expressed in the human oocyte than in the oocyte-specific antigen (Figure 1). Oocyte-specific antigen is expressed in a dose-dependent manner in the human oocyte, in contrast to the oocyte-specific antigen. Oocyte-specific antigen is found in the human oocyte, and oocyte-specific antigen is expressed in the human oocyte (Figure 2). Oocyte-specific antigen is expressed in the human oocyte, but oocyte-specific antigen is expressed only in the human oocyte.\n\nFigure 1. View largeDownload slide Oocyte-speci